{
 "title": "Bare Metal Hosts sample graph",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Instance",
    "query": "label_values(netdata_info, instance)"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "label_values(netdata_disk_io_KiB_persec_average, family)"
   },
   {
    "name": "fs",
    "label": "FS",
    "query": "label_values(netdata_disk_space_GiB_average, family)"
   },
   {
    "name": "swap",
    "label": "Swap",
    "query": "label_values(netdata_system_swap_MiB_average, dimension)"
   },
   {
    "name": "net",
    "label": "Network interfaces",
    "query": "label_values(netdata_net_net_kilobits_persec_average, family)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(netdata_services_mem_usage_MiB_average, dimension)"
   }
  ]
 },
 "panels": [
  {
   "title": "Host $hosts Resources Usage",
   "type": "bargauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\",instance=~\"$hosts\"})",
     "legendFormat": "Host CPU Usage"
    },
    {
     "expr": "sum(netdata_system_ram_MiB_average{dimension=\"used\",instance=~\"$hosts\"})  / sum(netdata_system_ram_MiB_average{instance=~\"$hosts\"})  * 100",
     "legendFormat": "Host RAM Usage"
    },
    {
     "expr": "sum(netdata_system_swap_MiB_average{dimension=\"used\",instance=~\"$hosts\"})  / sum(netdata_system_swap_MiB_average{instance=~\"$hosts\"})  * 100",
     "legendFormat": "Host Swap Usage"
    },
    {
     "expr": "sum(netdata_disk_space_GiB_average{instance=~\"$hosts\",family=~\"$fs\",dimension=\"used\"})  / sum(netdata_disk_space_GiB_average{instance=~\"$hosts\",family=~\"$fs\"})  * 100",
     "legendFormat": "Host Root FS Usage"
    }
   ]
  },
  {
   "title": "Resource  $hosts  Nodes",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "netdata_info{application=\"netdata\",instance=~\"$hosts\"}",
     "legendFormat": "{{instance}} | Name"
    },
    {
     "expr": "count(netdata_cpu_cpu_percentage_average{instance=~\"$hosts\",dimension=\"idle\"}) by (instance)",
     "legendFormat": "{{instance}} | cputo"
    },
    {
     "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} | cpusa"
    },
    {
     "expr": "netdata_system_cpu_percentage_average{chart=\"system.cpu\",dimension=\"idle\",family=\"cpu\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} | cpui"
    },
    {
     "expr": "netdata_system_intr_interrupts_persec_average{instance=~\"$hosts\",job=\"netdata\"} ",
     "legendFormat": "{{instance}} | cinterrupts"
    },
    {
     "expr": "netdata_system_ctxt_context_switches_persec_average{instance=~\"$hosts\"}",
     "legendFormat": "{{instance}} | cpuswitches"
    },
    {
     "expr": "sum(netdata_system_ram_MiB_average{instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} | ramto"
    },
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\",dimension=\"used\",family=\"ram\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} | ramu"
    },
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\",dimension=\"free\",family=\"ram\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} | ramf"
    },
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\",dimension=\"cached\",family=\"ram\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} | ramcached"
    },
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\",dimension=\"buffers\",family=\"ram\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} | rambuffer"
    },
    {
     "expr": "sum(netdata_services_mem_usage_MiB_average{instance=~\"$hosts\",dimension=~\"$service\"}) by (instance)",
     "legendFormat": "{{instance}} |  libvirt"
    },
    {
     "expr": "sum(netdata_disk_space_GiB_average{instance=~\"$hosts\",family=~\"$disk\"}) by (instance)",
     "legendFormat": "{{instance}} |  diskto"
    },
    {
     "expr": "sum(netdata_disk_space_GiB_average{instance=~\"$hosts\",family=~\"$fs\",dimension=\"used\"}) by (instance)",
     "legendFormat": "{{instance}} |  diskusa"
    },
    {
     "expr": "sum(netdata_disk_iotime_milliseconds_persec_average{family=~\"$disk\",dimension=\"reads\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} |  diskiotread"
    },
    {
     "expr": "sum(netdata_disk_iotime_milliseconds_persec_average{family=~\"$disk\",dimension=\"writes\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} |  diskiotwite"
    },
    {
     "expr": "sum(netdata_disk_io_KiB_persec_average{family=~\"$disk\",dimension=\"reads\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} |  ali1"
    },
    {
     "expr": "sum(netdata_disk_io_KiB_persec_average{family=~\"$disk\",dimension=\"writes\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} |  alinikou2"
    },
    {
     "expr": "netdata_disk_util___of_time_working_average{chart=\"disk_util.sda\",dimension=\"utilization\",family=~\"$disk\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} |  diskutiliz"
    },
    {
     "expr": "sum(netdata_system_swap_MiB_average{dimension=~\"$swap\",instance=~\"$hosts\"}) by (instance) ",
     "legendFormat": "{{instance}} |  swap"
    },
    {
     "expr": "sum(netdata_system_net_kilobits_persec_average{chart=\"system.net\",dimension=\"sent\",family=\"network\",instance=~\"$hosts\",job=\"netdata\"}) by (instance) ",
     "legendFormat": "{{instance}} |  netsend"
    },
    {
     "expr": "sum(netdata_system_net_kilobits_persec_average{chart=\"system.net\",dimension=\"received\",family=\"network\",instance=~\"$hosts\",job=\"netdata\"}) by (instance) ",
     "legendFormat": "{{instance}} |  netreceived"
    },
    {
     "expr": "Avg(netdata_net_net_kilobits_persec_average{family=~\"$net\",dimension=\"received\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} |  netinterrecie"
    },
    {
     "expr": "Avg(netdata_net_net_kilobits_persec_average{family=~\"$net\",dimension=\"sent\",instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} |  netintersent"
    },
    {
     "expr": "netdata_ipv4_packets_packets_persec_average{chart=\"ipv4.packets\",dimension=\"sent\",family=\"packets\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} |  packetsent"
    },
    {
     "expr": "netdata_ipv4_packets_packets_persec_average{chart=\"ipv4.packets\",dimension=\"received\",family=\"packets\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} |  packetrecieved"
    },
    {
     "expr": "netdata_ipv4_packets_packets_persec_average{chart=\"ipv4.packets\",dimension=\"delivered\",family=\"packets\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} |  packetdiliverd"
    },
    {
     "expr": "netdata_ipv4_tcpsock_active_connections_average{instance=~\"$hosts\"}",
     "legendFormat": "{{instance}} |  tcpconnec"
    }
   ]
  },
  {
   "title": "System active processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_system_active_processes_processes_average{instance=~\"$hosts\"}) ",
     "legendFormat": "Total System active processes"
    },
    {
     "expr": "sum(netdata_system_active_processes_processes_average{instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP sockets ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_ipv4_sockstat_sockets_sockets_average{instance=~\"$hosts\"}) ",
     "legendFormat": "Total tcp sockets used"
    },
    {
     "expr": "sum(netdata_ipv4_sockstat_tcp_sockets_sockets_average{chart=\"ipv4.sockstat_tcp_sockets\",dimension=\"timewait\",family=\"tcp\",instance=~\"$hosts\",job=\"netdata\"}) ",
     "legendFormat": "Total tcp sockets Time Waite"
    },
    {
     "expr": "sum(netdata_ipv4_sockstat_sockets_sockets_average{instance=~\"$hosts\"}) by (instance)",
     "legendFormat": "{{instance}} Socket Used"
    },
    {
     "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{chart=\"ipv4.sockstat_tcp_sockets\",dimension=\"timewait\",family=\"tcp\",instance=~\"$hosts\",job=\"netdata\"}",
     "legendFormat": "{{instance}} Socket Time Waite"
    }
   ]
  }
 ]
}